export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADS_LOADED_REQUEST = "ADS_LOADED_REQUEST";
export const ADS_LOADED_SUCCESS = "ADS_LOADED_SUCCESS";
export const ADS_LOADED_FAILURE = "ADS_LOADED_FAILURE";

export const AD_LOADED_REQUEST = "AD_LOADED_REQUEST";
export const AD_LOADED_SUCCESS = "AD_LOADED_SUCCESS";
export const AD_LOADED_FAILURE = "AD_LOADED_FAILURE";

export const TAGS_LOADED_REQUEST = "TAGS_LOADED_REQUEST";
export const TAGS_LOADED_SUCCESS = "TAGS_LOADED_SUCCESS";
export const TAGS_LOADED_FAILURE = "TAGS_LOADED_FAILURE";

export const AD_CREATED = "AD_CREATED";

export const USERINTERFACE_RESET_ERROR = "USERINTERFACE_RESET_ERROR";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const TOGGLE_RESULT = "TOGGLE_RESULT";

// export const AD_FILTERING = "AD_FILTERING";

export const AD_FILTERING_NAME = "AD_FILTERING_NAME";
export const AD_FILTERING_SALE = "AD_FILTERING_SALE";
export const AD_FILTERING_TAGS = "AD_FILTERING_TAGS";
export const AD_FILTERING_MIN_PRICE = "AD_FILTERING_MIN_PRICE";
export const AD_FILTERING_MAX_PRICE = "AD_FILTERING_MAX_PRICE";
