export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADS_LOADED = "ADS_LOADER";
export const AD_CREATED = "AD_CREATED";

export const USERINTERFACE_RESET_ERROR = "USERINTERFACE_RESET_ERROR";
